name: Test/Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm build
              run: |
                  npm ci
                  npm run build --if-present
              env:
                  CI: true
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm test
              run: |
                  npm ci
                  npm test --if-present
              env:
                  CI: true
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm run eslint
              run: |
                  npm ci
                  npm run eslint-quit --if-present
              env:
                  CI: true
